import{A as d,a as f,S as h}from"./assets/vendor-32dd1250.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(o){if(o.ep)return;o.ep=!0;const t=r(o);fetch(o.href,t)}})();function g(){new d(".about-me__accordion-container",{duration:400,showMultiple:!1,collapse:!0})}g();const v=document.querySelectorAll(".about-me__header");v.forEach(s=>{s.addEventListener("click",function(){const r=this.closest(".about-me__item").querySelector(".about-me__panel");r&&r.classList.toggle("visually-hidden")})});document.addEventListener("DOMContentLoaded",function(){const s=document.querySelectorAll(".swiper-slide");let e=0;function r(){s.forEach((n,u)=>{u===e?n.classList.add("color-slide"):n.classList.remove("color-slide")})}r();function a(){s[e].classList.remove("color-slide"),e=(e+1)%s.length,s[e].classList.add("color-slide")}document.querySelector(".swiper-button-next").addEventListener("click",function(){a(),setTimeout(r,1e3)}),s.forEach((n,u)=>{n.addEventListener("click",function(){e=u,r()})});const t=document.querySelector(".swiper");let i=0,c=!1;t.addEventListener("touchstart",function(n){i=n.touches[0].clientX,c=!0}),t.addEventListener("touchmove",function(n){if(!c)return;const l=n.touches[0].clientX-i;Math.abs(l)>50&&(l>0?e=e===0?s.length-1:e-1:e=e===s.length-1?0:e+1,r(),c=!1)})});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".faq-accordion").forEach(e=>{e.addEventListener("click",function(){const r=this.querySelector(".faq-arrow"),a=this.nextElementSibling;r.classList.toggle("rotate"),a.classList.toggle("visually-hidden")})}),new d(".faq-section",{duration:400,showFirstItem:!1})});f.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function w(){return(await f.get("/reviews")).data}function L(s){s.then(e=>{const r=e.map(({avatar_url:t,_id:i,author:c,review:n})=>{const l=n.length>180,m=l?"review-user-comment-collapsed":"",p=l?n.slice(0,180)+"...":n;return`<li class="review-carusel-list-item">
                <div class="user-review-container">
                    <img class="review-user-photo" src="${t}" alt="${i}">
                    <div class="user-data-review-container" data-review="${n}">
                        <h4 class="review-user-name">${c}</h4>
                        <p class="review-user-comment ${m}">${p}</p>
                        ${l?'<button class="toggle-btn">Згорнути</button>':""}
                    </div>
                </div>
            </li>`}).join(""),a=document.querySelector(".reviews-carusel");a.innerHTML=r,document.querySelectorAll(".toggle-btn").forEach(t=>{t.addEventListener("click",function(){const i=this.closest(".user-data-review-container"),c=i.querySelector(".review-user-comment"),n=i.dataset.review;c.classList.toggle("review-user-comment-collapsed"),c.classList.contains("review-user-comment-collapsed")?(c.textContent=n.slice(0,180)+"...",this.textContent="Розгорнути"):(c.textContent=n,this.textContent="Згорнути")})})}).catch(e=>{console.error("Not found",e)})}L(w());document.addEventListener("DOMContentLoaded",function(){new h(".swiper-container",{direction:"horizontal",Pagination:{el:".swiper-pagination"},Navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:!0,touch:!0,loop:!0})});
//# sourceMappingURL=commonHelpers.js.map
